# Generated by Django 5.1.4 on 2025-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.IntegerField(default='0', max_length=15),
        ),
    ]
