# Generated by Django 5.1.4 on 2025-03-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.IntegerField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="passport_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
