# Generated by Django 5.1.4 on 2025-03-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.IntegerField(blank=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="passport_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
