# Generated by Django 5.1.4 on 2025-03-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
