# Generated by Django 5.1.4 on 2025-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userprofile_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
