# Generated by Django 5.1.4 on 2025-03-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(help_text="Phone number must be entered in the format: '254.....'", max_length=20),
        ),
    ]
