# Generated by Django 5.1.4 on 2025-03-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatusEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Reviewed", "Reviewed"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interview", "Interview"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="You can use the following placeholders: {applicant_name}, {job_title}, {company}, {status}, {application_date}, {admin_message}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Application Status Email Template",
                "verbose_name_plural": "Application Status Email Templates",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="admin_message",
            field=models.TextField(
                blank=True,
                help_text="Optional message to include in the email to the applicant",
            ),
        ),
    ]
