# Generated by Django 5.1.4 on 2025-03-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationstatusemailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatusemailtemplate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interview', 'Interv   iew'), ('Reviewed', 'Reviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Shortlisted', 'Shortlisted')], max_length=20, unique=True),
        ),
    ]
