# Generated by Django 5.1.4 on 2025-03-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationstatusemailtemplate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Shortlisted', 'Shortlisted')], default='Pending', max_length=50),
        ),
    ]
