# Generated by Django 5.1.4 on 2025-03-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_country_country_code_country_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AlterField(
            model_name='job',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
