# Generated by Django 5.1.4 on 2025-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_max_salary_remove_job_salary_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='working_hours',
            field=models.CharField(default='40 hours per week', max_length=50),
        ),
    ]
