# Generated by Django 5.1.4 on 2025-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='working_hours',
            field=models.CharField(blank=True, default='40 hours per week', max_length=50),
        ),
    ]
